### ISSUE TITLE
Session expires after 35 minutes

### ISSUE THREAD

**Issue by mattimart** [paul1956/CareLink#58]
Carelink is working properly but after about 35 minutes the session expires and the program stops updating and needs a new login
![carelink_session_expire](https://github.com/paul1956/CareLink/assets/44461571/36b5dac4-ca24-4969-873e-4e8803bb17b1)

**Comment by paul1956** [comment]
@mattimart Fixed in CareLink4.0.1.1x64. Thanks for the catch.

Please close if you agree.

**Comment by maxdego** [comment]
new version CareLink4.0.1.1x64 downloaded and installed, but the problem still remains

**Comment by mattimart** [comment]
> @mattimart Fixed in CareLink4.0.1.1x64. Thanks for the catch.
> 
> Please close if you agree.

Carelink.exe in release 4.0.1.1 is still 4.0.1.0 
![image](https://github.com/paul1956/CareLink/assets/44461571/fd72a3b0-cfe1-4eed-ab34-0c4d302966e9)

**Comment by maxdego** [comment]
Carelink.exe release 4.0.1.1 is still 4.0.1.0
Yes, I had already noticed it as soon as I installed it, but I thought the login problem had been solved

**Comment by paul1956** [comment]
Are you saying version is wrong or issue is still there or both?I will fix version number today to 4.0.1.2. And also verify issue 35 minute failure is fixed. The fix in 4.0.0.1 was to address new SmartGuard information in an updated pump in Ireland, it only effected users there.Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Apr 4, 2024, at 9:03 AM, maxdego ***@***.***> wrote:﻿
Carelink.exe release 4.0.1.1 is still 4.0.1.0
Yes, I had already noticed it as soon as I installed it, but I thought the login problem had been solved

**Comment by maxdego** [comment]
both, version is wrong and issue is still there

**Comment by paul1956** [comment]
@maxdego   The timeout of 35 minutes (it was 24 hours) is controlled by Medtronic, the same happens with a Browser but you should be able to redo Captcha and continue if not let me know.
